# Background and foreground colors
background = #1D1218
foreground = #E5D8F0

# Standard colors
palette = 0=#1D1218
palette = 1=#D75551
palette = 2=#73C473
palette = 3=#DAA66C
palette = 4=#C3C6DA
palette = 5=#BFA6BF
palette = 6=#9ED6D6
palette = 7=#E5D8F0

# Bright colors
palette = 8=#987D8B
palette = 9=#EC9A98
palette = 10=#AFE1AF
palette = 11=#EDCDA9
palette = 12=#D3D6E5
palette = 13=#D9C9D9
palette = 14=#C1E7E7
palette = 15=#E7D9F2
