background            #1D1218
foreground            #E5D8F0

# black
color0  #1D1218
color8  #987D8B

# red
color1  #D75551
color9  #EC9A98

# green
color2  #73C473
color10 #AFE1AF

# yellow
color3  #DAA66C
color11 #EDCDA9

# blue
color4  #C3C6DA
color12 #D3D6E5

# magenta
color5  #BFA6BF
color13 #D9C9D9

#cyan
color6  #9ED6D6
color14 #C1E7E7

#white
color7  #E5D8F0
color15 #E7D9F2


