# Global Styling
font= Inter Nerd Font 11
background-color={{colors.surface.dark.hex}}
text-color={{colors.primary.dark.hex}}
border-color={{colors.primary.dark.hex}}
border-size=2
border-radius=12
width=340
margin=10
padding=10

# Global Timeout (in milliseconds)
default-timeout=5000

# Urgency Levels
[urgency=low]
border-color={{colors.tertiary.dark.hex}}
default-timeout=2000

[urgency=critical]
border-color={{colors.error.dark.hex}}
default-timeout=0

default-timeout=3000

[urgency=low]
default-timeout=2000

[urgency=critical]
default-timeout=0