background            #151217
foreground             #fbf2fa

color0                 #4b454d
color8                 #a59da7

color1                 #ffb4ab
color9                 #ffb4ab

color2                 #f3b7bc
color10                #f3b7bc

color3                 #d1c1d9
color11                #d1c1d9

color4                 #dcb9f8
color12                #dcb9f8

color5                 #f3b7bc
color13                #f3b7bc

color6                 #d1c1d9
color14                #d1c1d9

color7                 #fbf2fa
color15                #fbf2fa

cursor                 #dcb9f8
selection_background   #dcb9f8
selection_foreground   #151217
